Add `password_command for sasl and `nick_password`
squidowl/halloy pull request #583
Opened 2024-09-20 15:22 UTC by 4e554c4c

This commit builds off of #552 and allows the user to supply a command instead of a password file anywhere that a password file is used. If the password command ends unsuccessfully, then an error is displayed.

Trailing whitespace is now trimmed from password commands, as it is commonplace for commands to leave a trailing newline after the password they output.

Resolves #580

2024-09-21 20:35 UTC, casperstorm commented
I think this deserves a entry in CHANGELOG. I'll do proper review tomorrow.

2024-09-22 13:44 UTC, casperstorm commented on data/src/config.rs
> +}
`Error::Read(_)` isn't the best name anymore i'd say. Lets rename it now that you are touching these files, and while doing so rename this `fn` as well to make it more clear just by reading it.

Perhaps the error could be something like
`Error::Config(_)` or `Error::LoadConfigFile(_)` to keep it similar to `LoadSounds`.
*

2024-09-22 13:44 UTC, casperstorm requested changes
A single nit regarding naming, but overall it looks great.

2024-09-23 20:17 UTC, casperstorm approved these changes
Looks good to me. @tarkah do you have anything for this?

2024-09-24 17:45 UTC, tarkah requested changes

2024-09-24 17:45 UTC, tarkah commented on data/src/server.rs
> +                    return Err(Error::Parse(DUP_PASS_MSG.to_string()));
Nit: Just make these separate Error variants so we don't need to use `Parse` plus some const string for each error type.

2024-09-24 17:45 UTC, tarkah commented on src/main.rs
> +                if config::has_yaml_config() {
We really should add a new `config::Error` variant for `config::Error::ConfigMissing { has_yaml_config: bool }` where we check if `path.exists` and if not, we can populate the error with `config::has_yaml_config`.

Then under this branch, we can simply check if error is `Error::ConfigMissing { has_yaml_config: true }` for `Screen::Migration`.

The `ConfigMissing { has_yaml_config: false }` can then route to `Screen::Welcome`. We only want to route here if the config is missing & no yaml config exits. Any parsing errors should truly route to `Screen::Help` w/ the error

2024-09-26 14:03 UTC, tarkah approved these changes
Changes look great! I think that cleaned it up very nicely. Thanks for tackling this

2024-09-27 06:31 UTC, merged

2024-09-27 06:31 UTC, casperstorm commented
Thanks for yet another good PR.